### PR TITLE
try/catch all api calls widgets make

### LINKED ISSUE #61: Null Checking
Check for Null return from API calls. If an API is called and returns Null we currently aren't checking for that. This will crash the entire app and make it impossible to use the app until the API call returns non-null. Which could take a while depending on why the API is returning Null (i.e. out of uses for the day.)

### PR DESCRIPTION
**Pull request by heykc**
## Fixes
Fixes: #61 

## Description
I've implemented try/catches for every API currently being used in the app. Each catch handles an error that could be thrown by a fetch and at times also handles default values that may need to be passed if the fetch request fails.

I also rewrote the email fetch to stop fetching the moment it comes across a bad request when fetching each single email. This will keep the request quota low for Gmail's API. 

## Tests
Please test each widget vigorously. I did not see any built in component tests, so you will have to test each widget manually.

### CODE REVIEW

**Comment by J8cob1** [comment]
Approving deployment

**Comment by J8cob1** [comment]
We are getting an error: "Cannot find module: 'deep-diff'. Make sure this package is installed."

Is the package.json file updated?

**Comment by J8cob1** [comment]
And also, now that this project is more than just a class project, we might consider looking into different deployment solutions (i.e: one that doesn't require me to error check all of the vercel deployments--because I might not be here 24/7)

**Comment by heykc** [comment]
That's my fault. it was a small package that I meant to remove completely. I forgot to remove it from the file that was importing it. I'll make that change and re-upload

**Pull request merged**
